In [1]:
import pandas as pd
import json

In [2]:
df = pd.read_excel('data/DATA.xlsx',sheet_name='user')

In [3]:
df.isnull().sum()

User                0
State               0
ID                  0
Name                0
HQ                  0
User Designation    0
Mobile              0
Password            0
dtype: int64

In [4]:
df.columns

Index(['User', 'State', 'ID', 'Name', 'HQ', 'User Designation', 'Mobile',
       'Password'],
      dtype='object')

In [5]:
df = df[['State','User Designation','HQ','User','Password']]

In [6]:
df.sort_values(by=['State','User Designation','HQ','User'],inplace=True)

In [7]:
df.head(5)

       State User Designation        HQ                      User  Password
37   Gujarat              ASM      Bhuj    Sahil Mansuri|PGGJ1005      5896
46   Gujarat              ASM    Rajkot   Hitesh Thakkar|PGGJ1004      9493
51   Gujarat              ASM    Rajkot   Vinesh Trivedi|PGGJ1006      7460
335  Gujarat              ASM     Surat      Jatin Saini|PGGJ1055      4518
58   Gujarat              ASM  Vadodara  Girwat Sing Raj|PGGJ1003      4330

In [8]:
df1 = df[['State','User Designation','HQ','User','Password']]

In [9]:
df1

,State,User Designation,HQ,User,Password
37,Gujarat,ASM,Bhuj,Sahil Mansuri|PGGJ1005,5896
46,Gujarat,ASM,Rajkot,Hitesh Thakkar|PGGJ1004,9493
51,Gujarat,ASM,Rajkot,Vinesh Trivedi|PGGJ1006,7460
335,Gujarat,ASM,Surat,Jatin Saini|PGGJ1055,4518
58,Gujarat,ASM,Vadodara,Girwat Sing Raj|PGGJ1003,4330
...,...,...,...,...,...
216,Uttarakhand,SR,Kichha,Sanjeev Kumar|PGUK1009,6574
218,Uttarakhand,SR,Kotdwar,Rakesh Singh|PGUK1013,3128
253,Uttarakhand,SR,Rishikesh,Deepak|PGUK1027,2968
239,Uttarakhand,SR,Roorkee,Krish|PGUK1025,4082
309,Uttarakhand,SR,Vikasnagar,Manish Verma|PGUK1030,2011

In [10]:
df11 = df1.sample(2)

In [11]:
df1.columns

Index(['State', 'User Designation', 'HQ', 'User', 'Password'], dtype='object')

In [12]:
# Create nested dictionary with password at DB level
nested = {}

for _, row in df1.iterrows():
    state = row['State']
    ss = row['User Designation']
    db = row['HQ']
    ws = row['User'] # USER
    pwd = row['Password']

    state_dict = nested.setdefault(state, {})
    ss_dict = state_dict.setdefault(ss, {})
    hq_dict = ss_dict.setdefault(db, {})
    db_dict = hq_dict.setdefault(ws, {"password": pwd, "user": []})

    db_dict["user"].append(ws)

# Save
with open("data/dropdown.json", "w") as f:
    json.dump(nested, f, indent=4)